#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -0 -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 3 -font "Fantasque Sans Mono 10" <<< " Lock| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) loginctl lock-session ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
